<a href="https://colab.research.google.com/github/MrKeeplearning/dap-course/blob/main/lecture/lecture2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Understanding NumPy Array

## 1.1. Creating Numpy Array

In [1]:
import numpy as np

In [2]:
# Creating an array
a = np.array([2, 4, 6, 8, 10])
print(a)
a

[ 2  4  6  8 10]


array([ 2,  4,  6,  8, 10])

In [3]:
# Creating an array using arange()
a = np.arange(1, 20)
# step을 사용해서 홀수만 출력할 수도 있다.
b = np.arange(1, 20, 2)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


### 💡 Other functions

In [4]:
# Create an array of all zeros
p = np.zeros((3, 3))
print(p)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Create an array of all ones
q = np.ones((2, 2))
print(q)

[[1. 1.]
 [1. 1.]]


In [6]:
# Create a constant array
r = np.full((2,2), 4)
print(r)

[[4 4]
 [4 4]]


In [7]:
# Create a 2x2 identity matrix
s = np.eye(4)
print(s)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# Create an array filled with random values
t = np.random.random((3,3))
print(t)

[[0.02670362 0.51875655 0.15292107]
 [0.70272072 0.70912676 0.67033655]
 [0.83575364 0.77696292 0.23643352]]


### 💡 linspace
linspace 함수는 다음과 같은 형식을 가지고 있다.
```
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```
start는 배열의 시작값, stop은 배열의 끝값이고, num은 start와 stop 사이를 몇 개의 일정한 간격으로 요소를 만들 것인지 나타내는 것이다. 만약 num을 생략하게 되면 default로 지정된 50개로 나누어 1차원 배열을 생성한다.

좀 더 자세한 내용은 [공식문서](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#)를 확인하자.


In [9]:
t = np.linspace(1, 20)
print(t)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


arange 함수가 정수들만 다루었다면, linspace 같은 경우에는 특정 시작 포인트부터 end point까지 소수점으로 균일하게 나누어서 만들어 보여준다는 차이점이 있다.

## 1.2. Array Features

기본적으로 NumPy array는 한 가지 데이터 타입으로 이루어져 있다. 따라서, 한 칸 한 칸이 int64로 되어 있고, 아래의 예시의 경우 int64의 10개에 해당하는 값으로 storage size가 정해져 있다.

In [10]:
# Creating an array using arange()
a = np.arange(1, 11)
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


일반적인 파이썬의 리스트를 사용해서 사이즈가 같은 두 리스트의 값을 합하려면 생각보다 복잡하다. 단순히 두 개의 리스트를 더하면 생각했던 것과 다른 결과가 출력된다.

In [11]:
lst1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lst2 = [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
lst3 = lst1 + lst2
print(lst3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


만약 사이즈가 동일한 두 개의 리스트에서 동일한 위치에 있는 값들끼리 더한 결과를 원한다면 아래와 같이 코드를 작성해야 한다.

In [12]:
lst3 = []
for a, b in zip(lst1, lst2):
  lst3.append(a + b)
print(lst3)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


하지만, numpy를 사용하면 훨씬 더 간편하고 깔끔하게 코드를 작성할 수 있다.

In [13]:
a = np.arange(1, 11)
b = np.arange(11, 21)
c = a + b
print(c)

[12 14 16 18 20 22 24 26 28 30]


## 1.3. Data type

dtype 이라는 명령어를 통해서 선언되어 있는 배열의 타입이 무엇인지 바로 확인할 수도 있다. 혹은 데이터 타입이 무엇인지 먼저 선언해줌으로써 해당 배열의 데이터 타입을 정할 수도 있다.

In [14]:
# Creating an array
import numpy as np
a = np.array([2,4,6,8,10])
print(a.dtype)

int64


In [15]:
# Create numpy array using arange() function
var1 = np.arange(1, 11, dtype='f')
print(var1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### Changing the Data Type

### ◼ astype( )
converts the data type

In [16]:
# create an array
arr = np.arange(1, 10).reshape(3,3)
print("Integer Array:\n", arr)

Integer Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# Change datatype of array
arr = arr.astype(float)
print("Float Array:\n", arr)

# Check new data type of array
print("Changed Datatype:", arr.dtype)

Float Array:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Changed Datatype: float64


### ◼  tolist( )
coverts the data type of the array.

In [18]:
# Create an array
arr = np.arange(1, 10)

# Convert NumPy array to Python List
list1 = arr.tolist()
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


## 1.4 Manipulating

### ◼ reshape( )
reshape( ) will change the shape of the array

In [19]:
# Create an array
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
# Reshape the array dimension
new_arr=arr.reshape(4,3)
print(new_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [21]:
# Reshape the array dimension
new_arr2 = arr.reshape(2, -1)
print(new_arr2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### ◼ resize( )
reshape은 원래 array를 copy해 온 다음에 reshape를 적용하는 것이고, resize는 original array에 접근해서 변환한다.

In [22]:
# Create an array
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
# resize the matrix with reshape( )
# reshape이 arr에 적용되었지만 orginal array에 변화가 적용되지는 않는다.

arr.reshape(4, 3)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
arr.resize(4, 3)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### ◼ flatten( )
* flatten( ) transforms an n-dimensional array into a one-dimensional array
* reshape과 마찬가지로 original array에 영향을 미치지 않는다.

In [25]:
# Create an array
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# flatten the array
print(arr.flatten())
print(arr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
# reshape(-1)을 사용해서도 flatten()과 동일한 결과를 얻을 수 있다.
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8 9]


### ◼ ravel( )
ravel( ) is similar to the flatten( ) but it returns the reference of the original array.
* faster than flatten.
* affects on original array. 

In [72]:
# Create an array
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

# ravel( ) function
print(arr.ravel())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


flatten은 original array를 접근한 것이 아니라 copy해 온 다음에 적용하는 것이기 때문에 실제 array에는 영향이 없다.

In [76]:
arr.flatten()[8]=999
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


반면 ravel은 original array를 건드리는 것이기 때문에 값이 변한 것을 확인할 수 있다.

In [30]:
arr.ravel()[8]=999
print(arr)

[[  1   2   3]
 [  4   5   6]
 [  7   8 999]]


## 1.5. The Stacking

### ◼ hstack( )
* horizontal stacking
* alt.: concatenate()
* for 1d array: you can also use column_stack()

In [31]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
arr2 = 2*arr1
print(arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [33]:
arr3 = np.hstack((arr1, arr2))
print(arr3)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


In [34]:
# Horizontal stacking using concatenate( ) function
# axis=0은 row를 기준으로, axis=1은 column을 기준으로 concatenate한다.

arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


In [35]:
# Using column_stack() for 1d array.
arr1 = np.arange(1, 4)
arr2 = np.arange(4, 7)
arr3 = np.column_stack((arr1, arr2))
print(arr3)

[[1 4]
 [2 5]
 [3 6]]


### ◼ vstack( )
* vertical stacking
* alt.: concatenate( , axis=0)
* for 1d array: you can also use row_stack()

In [36]:
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
arr2 = 2*arr1
print(arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [38]:
arr5 = np.vstack((arr1, arr2))
print(arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [39]:
arr6 = np.concatenate((arr1, arr2), axis=0)
print(arr6)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [40]:
# Using row_stack() for 1d array
arr1 = np.arange(1, 4)
arr2 = np.arange(4, 7)
arr3 = np.row_stack((arr1, arr2))
print(arr3)

[[1 2 3]
 [4 5 6]]


### ◼ dstack( )
depth stacking, join along with a third axis(depth)

In [41]:
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)
arr2 = 2*arr1
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [42]:
arr7 = np.dstack((arr1, arr2))
print(arr7)

[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]
  [ 6 12]]

 [[ 7 14]
  [ 8 16]
  [ 9 18]]]


In [43]:
print(arr7.shape)

(3, 3, 2)


## 1.6. Partitioning

### ◼ hsplit( )
the given array is divided into equal sub-arrays along the horizontal axis.

In [44]:
# Create an array
arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
# Perform horizontal splitting
arr_hor_split=np.hsplit(arr,3)
print(arr_hor_split)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


### ◼ vsplit()
the given array is divided into equal sub-arrays along the vertical axis.

In [46]:
# Create an array
arr = np.arange(1, 10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
# vertical split
arr_ver_split=np.vsplit(arr, 3)
print(arr_ver_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


### ◼ split()
the given array is divided into equal sub-arrays along the given axis.
* axis=0; vertical
* axis=1; horizontoal

In [48]:
# split with axis=0
arr_split=np.split(arr, 3, axis=0)
print(arr_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [49]:
# split with axis=1
arr_split=np.split(arr, 3, axis=1)
print(arr_split)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


## 1.7. Numpy Views and Copies

In [50]:
# Create NumPy Array
arr = np.arange(1, 5).reshape(2,2)
print(arr)

# Create shallow copy using View
arr_view=arr.view()
print(arr_view)

# Create Deep Copy
arr_copy=arr.copy()
print(arr_view)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [51]:
# Update the values of original array
arr[1] = [99, 89]

# Check values of array view
print("View Array:\n", arr_view)

# Check values of array copy
print("Copied Array:\n", arr_copy)

View Array:
 [[ 1  2]
 [99 89]]
Copied Array:
 [[1 2]
 [3 4]]


## 1.8. Slicing NumPy Arrays

In [52]:
# Create NumPy Array
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [53]:
print(arr[3:6])

[3 4 5]


In [54]:
print(arr[3:])

[3 4 5 6 7 8 9]


In [55]:
print(arr[-3:])

[7 8 9]


In [56]:
print(arr[2:7:2])

[2 4 6]


## 1.9. Boolean Indexing
* Boolean indexing returns elements that have a true value for the Boolean expression

In [57]:
# Create NumPy Array
arr = np.arange(21, 41, 2)
print("Original Array:\n", arr)

Original Array:
 [21 23 25 27 29 31 33 35 37 39]


In [58]:
print(arr>30)

[False False False False False  True  True  True  True  True]


In [59]:
# Boolean Indexing
print("After Boolean Condition:", arr[arr>30])

After Boolean Condition: [31 33 35 37 39]


## 1.10. Fancy Indexing
* Fancy indexing is a special type of indexing in which elements of an array are selected by an array of indices.

In [60]:
# Create NumPy Array
arr = np.arange(1, 21).reshape(5, 4)
print("Original Array:\n", arr)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [61]:
# Selecting 1st and 2nd row
indices = [1,2]
print("Selected 1st and 2nd Row:\n", arr[indices])

Selected 1st and 2nd Row:
 [[ 5  6  7  8]
 [ 9 10 11 12]]


In [62]:
# Selecting 2nd and 3rd row
indices = [2, 3]
print("Selected 2nd and 3rd Row:\n", arr[indices])

Selected 2nd and 3rd Row:
 [[ 9 10 11 12]
 [13 14 15 16]]


In [63]:
# Selecting 1st and 2nd column
indices = [1,2]
print("Selected 1st and 2nd Column:\n", arr[:, indices])

Selected 1st and 2nd Column:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]


In [64]:
# Selecting 2nd and 3rd column
indices = [2,3]
print("Selected 2nd and 3rd Column:\n", arr[:, indices])

Selected 2nd and 3rd Column:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]]


## 1.11. Broadcasting Arrays
* Python lists do not support direct vectorizing arithmetic operations.
* NumPy offers a faster-vectorized array operation compared to Python list loop-based operations.

In [65]:
# Create NumPy Array
arr1 = np.arange(1,5).reshape(2,2)
print(arr1)

[[1 2]
 [3 4]]


In [66]:
# Create another NumPy Array
arr2 = np.arange(5, 9).reshape(2,2)
print(arr2)

[[5 6]
 [7 8]]


In [67]:
# Add two matrices
print(arr1+arr2)

[[ 6  8]
 [10 12]]


In [68]:
# Multiply two matrices
print(arr1*arr2)

[[ 5 12]
 [21 32]]


In [69]:
# Add a scaler value
print(arr1 + 3)

[[4 5]
 [6 7]]


In [70]:
# Multiply with a scalar value
print(arr1*3)

[[ 3  6]
 [ 9 12]]


# 2. Pandas

## Creating Pandas DataFrames

In [95]:
import pandas as pd
df = pd.DataFrame()
df.head()

Empty DataFrame
Columns: []
Index: []

In [96]:
# Create dictionary of list
data = {'Name': ['Vijay', 'Sundar', 'Satyam', 'Indira'],
        'Age': [23, 45, 46, 52]}
df = pd.DataFrame(data)
df.head()

Name  Age
0   Vijay   23
1  Sundar   45
2  Satyam   46
3  Indira   52

In [98]:
# Pandas DataFrame by lists of dicts
# Initialize data to lists.
data = [{'Name': 'Vijay', 'Age': 23},
        {'Name': 'Sundar', 'Age': 25},
        {'Name': 'Shankar', 'Age': 26}]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df.head()

Name  Age
0    Vijay   23
1   Sundar   25
2  Shankar   26

## Pandas Series

In [100]:
# Creating Pandas Series using Dictionary
dict1 = {0: 'Ajay', 1: 'Jay', 2: 'Vijay'}
# Create Pandas Series
series = pd.Series(dict1)
series

0     Ajay
1      Jay
2    Vijay
dtype: object

In [101]:
# load Pandas and NumPy
import pandas as pd
import numpy as np
# Create NumPy array
arr = np.array([51, 65, 48, 59, 68])
# Create Pandas Series
series = pd.Series(arr)
series

0    51
1    65
2    48
3    59
4    68
dtype: int64

## Load CSV using Pandas

In [102]:
!git clone https://github.com/PacktPublishing/Python-Data-Analysis-Third-Edition

Cloning into 'Python-Data-Analysis-Third-Edition'...
remote: Enumerating objects: 288, done.
remote: Counting objects: 100% (178/178), done.
remote: Compressing objects: 100% (149/149), done.
remote: Total 288 (delta 58), reused 83 (delta 7), pack-reused 110
Receiving objects: 100% (288/288), 7.88 MiB | 18.04 MiB/s, done.
Resolving deltas: 100% (87/87), done.


In [103]:
# Import pandas
import pandas as pd

# Load data using read_csv()
df = pd.read_csv("Python-Data-Analysis-Third-Edition/Chapter02/WHO_first9cols.csv")

# show initial 5 records
df.head()

Country  ...  Population (in thousands) total
0  Afghanistan  ...                          26088.0
1      Albania  ...                           3172.0
2      Algeria  ...                          33351.0
3      Andorra  ...                             74.0
4       Angola  ...                          16557.0

[5 rows x 9 columns]

## Extract Series from DataFrame

In [104]:
# Select a series
country_series = df['Country']
print(country_series)

0             Afghanistan
1                 Albania
2                 Algeria
3                 Andorra
4                  Angola
              ...        
197               Vietnam
198    West Bank and Gaza
199                 Yemen
200                Zambia
201              Zimbabwe
Name: Country, Length: 202, dtype: object


In [105]:
# Describe the dataset
df.describe()

CountryID  ...  Population (in thousands) total
count  202.000000  ...                     1.890000e+02
mean   101.500000  ...                     3.409964e+04
std     58.456537  ...                     1.318377e+05
min      1.000000  ...                     2.000000e+00
25%     51.250000  ...                     1.328000e+03
50%    101.500000  ...                     6.640000e+03
75%    151.750000  ...                     2.097100e+04
max    202.000000  ...                     1.328474e+06

[8 rows x 8 columns]

In [106]:
df.count()

Country                                                   202
CountryID                                                 202
Continent                                                 202
Adolescent fertility rate (%)                             177
Adult literacy rate (%)                                   131
Gross national income per capita (PPP international $)    178
Net primary school enrolment ratio female (%)             179
Net primary school enrolment ratio male (%)               179
Population (in thousands) total                           189
dtype: int64

In [107]:
# Group by dataframe on the basis of Continent column
df.groupby('Continent').mean()

CountryID  ...  Population (in thousands) total
Continent              ...                                 
1          110.238095  ...                     16843.350000
2          100.333333  ...                     17259.627451
3           99.354167  ...                     16503.195652
4           56.285714  ...                     73577.333333
5           94.774194  ...                     15637.241379
6          121.228571  ...                     25517.142857
7           80.777778  ...                    317683.666667

[7 rows x 7 columns]

## Joining

In [111]:
dest = pd.read_csv("Python-Data-Analysis-Third-Edition/Chapter02/dest.csv")
tips = pd.read_csv("Python-Data-Analysis-Third-Edition/Chapter02/tips.csv")

In [113]:
dest.head()

EmpNr       Dest
0      5  The Hague
1      3  Amsterdam
2      9  Rotterdam

In [114]:
tips.head()

EmpNr  Amount
0      5    10.0
1      9     5.0
2      7     2.5

In [118]:
# Join DataFrames using Inner Join
df_inner = pd.merge(dest, tips, on='EmpNr', how='inner')
df_inner.head()

EmpNr       Dest  Amount
0      5  The Hague    10.0
1      9  Rotterdam     5.0

In [119]:
# Join DataFrames using Outer Join
df_inner = pd.merge(dest, tips, on='EmpNr', how='outer')
df_inner.head()

EmpNr       Dest  Amount
0      5  The Hague    10.0
1      3  Amsterdam     NaN
2      9  Rotterdam     5.0
3      7        NaN     2.5

In [120]:
# Join DataFrames using Right Outer Join
df_inner = pd.merge(dest, tips, on='EmpNr', how='right')
df_inner.head()

EmpNr       Dest  Amount
0      5  The Hague    10.0
1      9  Rotterdam     5.0
2      7        NaN     2.5

## Count Missing Values

In [126]:
df.isnull()

Country  ...  Population (in thousands) total
1      False  ...                            False
2      False  ...                            False
4      False  ...                            False
6      False  ...                            False
7      False  ...                            False
..       ...  ...                              ...
195    False  ...                            False
196    False  ...                            False
197    False  ...                            False
199    False  ...                            False
200    False  ...                            False

[118 rows x 9 columns]

In [123]:
# Count missing values in DataFrame
df.isnull().sum()

Country                                                    0
CountryID                                                  0
Continent                                                  0
Adolescent fertility rate (%)                             25
Adult literacy rate (%)                                   71
Gross national income per capita (PPP international $)    24
Net primary school enrolment ratio female (%)             23
Net primary school enrolment ratio male (%)               23
Population (in thousands) total                           13
dtype: int64

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 9 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   Country                                                 202 non-null    object 
 1   CountryID                                               202 non-null    int64  
 2   Continent                                               202 non-null    int64  
 3   Adolescent fertility rate (%)                           177 non-null    float64
 4   Adult literacy rate (%)                                 131 non-null    float64
 5   Gross national income per capita (PPP international $)  178 non-null    float64
 6   Net primary school enrolment ratio female (%)           179 non-null    float64
 7   Net primary school enrolment ratio male (%)             179 non-null    float64
 8   Population (in thousands) total          

In [128]:
# Drop all the missing values
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118 entries, 1 to 200
Data columns (total 9 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   Country                                                 118 non-null    object 
 1   CountryID                                               118 non-null    int64  
 2   Continent                                               118 non-null    int64  
 3   Adolescent fertility rate (%)                           118 non-null    float64
 4   Adult literacy rate (%)                                 118 non-null    float64
 5   Gross national income per capita (PPP international $)  118 non-null    float64
 6   Net primary school enrolment ratio female (%)           118 non-null    float64
 7   Net primary school enrolment ratio male (%)             118 non-null    float64
 8   Population (in thousands) total          

In [130]:
# Fill missing value with 0
df = pd.read_csv("Python-Data-Analysis-Third-Edition/Chapter02/WHO_first9cols.csv")
df.fillna(0, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 9 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   Country                                                 202 non-null    object 
 1   CountryID                                               202 non-null    int64  
 2   Continent                                               202 non-null    int64  
 3   Adolescent fertility rate (%)                           202 non-null    float64
 4   Adult literacy rate (%)                                 202 non-null    float64
 5   Gross national income per capita (PPP international $)  202 non-null    float64
 6   Net primary school enrolment ratio female (%)           202 non-null    float64
 7   Net primary school enrolment ratio male (%)             202 non-null    float64
 8   Population (in thousands) total          

## Dealing with Dates

In [131]:
# Date range function
pd.date_range('01-01-2000', periods=45, freq='D')

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08',
               '2000-01-09', '2000-01-10', '2000-01-11', '2000-01-12',
               '2000-01-13', '2000-01-14', '2000-01-15', '2000-01-16',
               '2000-01-17', '2000-01-18', '2000-01-19', '2000-01-20',
               '2000-01-21', '2000-01-22', '2000-01-23', '2000-01-24',
               '2000-01-25', '2000-01-26', '2000-01-27', '2000-01-28',
               '2000-01-29', '2000-01-30', '2000-01-31', '2000-02-01',
               '2000-02-02', '2000-02-03', '2000-02-04', '2000-02-05',
               '2000-02-06', '2000-02-07', '2000-02-08', '2000-02-09',
               '2000-02-10', '2000-02-11', '2000-02-12', '2000-02-13',
               '2000-02-14'],
              dtype='datetime64[ns]', freq='D')

In [132]:
# Convert argument to datetime
pd.to_datetime('1/1/1970')

Timestamp('1970-01-01 00:00:00')

In [134]:
# Convert argument to datetime in specified format
pd.to_datetime(['20200101', '20200102'], format='%Y%m%d')

DatetimeIndex(['2020-01-01', '2020-01-02'], dtype='datetime64[ns]', freq=None)

In [136]:
# Handle value error
pd.to_datetime(['20200101', 'not a date'], errors='coerce')

DatetimeIndex(['2020-01-01', 'NaT'], dtype='datetime64[ns]', freq=None)